[project]
name = "prediction-appart"
version = "0.1.0"
description = "PrÃ©diction de prix d'appartement"
requires-python = ">=3.10"
dependencies = [
    "pandas",
    "scikit-learn",
    "matplotlib",
    "xgboost"
]